### ISSUE TITLE
Support for newer version of hostapd in OpenWrt master

### ISSUE THREAD

**Issue by jmccrohan** [awilliams/wifi-presence#12]
Hi Adam,

I recently updated my APs to the latest OpenWrt master and have noted these new errors in the log:

```
root@openwrt-ap:~# logread | grep wifi-presence
Sat Nov 19 12:11:44 2022 daemon.err wifi-presence[4190]: Error: invalid MAC address "1a:xx:xx:xx:xx:xx auth_alg=open"
Sat Nov 19 12:31:51 2022 daemon.err wifi-presence[4282]: Error: invalid MAC address "34:xx:xx:xx:xx:xx auth_alg=open"
Sat Nov 19 13:07:59 2022 daemon.err wifi-presence[4390]: Error: invalid MAC address "34:xx:xx:xx:xx:xx auth_alg=open"
Sat Nov 19 13:10:03 2022 daemon.err wifi-presence[4573]: Error: invalid MAC address "60:xx:xx:xx:xx:xx auth_alg=ft"
Sat Nov 19 13:11:06 2022 daemon.err wifi-presence[4597]: Error: invalid MAC address "60:xx:xx:xx:xx:xx auth_alg=ft"
Sat Nov 19 13:20:16 2022 daemon.err wifi-presence[4608]: Error: invalid MAC address "60:xx:xx:xx:xx:xx auth_alg=ft"
```

Doing a bit of digging, I think the issue was introduced here: https://github.com/openwrt/openwrt/commit/8cb995445a26ee124e40b8ef97cc0ddd9d10f82a

Could you take a look please? Happy to sponsor any package merge requests if needed.

Cheers,
Jon

**Comment by awilliams** [comment]
Thanks @jmccrohan for the bug report and great pointer to the related hostapd commit. That indeed looks like the breaking commit. 

In #13, I added support for these new CONNECT messages. I'll next update the package in OpenWrt.

**Comment by awilliams** [comment]
https://github.com/openwrt/packages/pull/19944

**Comment by jmccrohan** [comment]
@awilliams merged.

Thanks a million for the quick turnaround on this!
